# Generated by Django 3.0 on 2019-12-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("bills", "0002_auto_20191210_2152")]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        )
    ]
