# Generated by Django 3.0 on 2019-12-22 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("bills", "0003_auto_20191211_2056")]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="bills.Event",
            ),
        )
    ]
