# Generated by Django 3.0.2 on 2020-01-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("bills", "0009_auto_20200108_1105")]

    operations = [
        migrations.RemoveField(model_name="event", name="users"),
        migrations.AddField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="bills.Participant",
            ),
        ),
    ]
