# Generated by Django 3.0 on 2020-04-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("bills", "0011_auto_20200108_1432")]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="username",
            field=models.CharField(max_length=100),
        )
    ]
