# Generated by Django 3.0 on 2020-04-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_auto_20200402_0347'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('event', 'username')},
        ),
    ]
