name: Python application

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --deploy --system --dev
      - name: Set SECRET_KEY
        run: export SECRET_KEY="dummy"
      - name: Pylint
        run: pylint shared_bills bills
      - name: Black
        run: black --check ./
      - name: Pytest
        run: pytest
